export const chemistryTopics = [
  {
    id: "atomic-structure",
    slug: "atomic-structure",
    icon: "⚛️",
    color: "from-blue-500 to-blue-600",
    bg: "bg-blue-50",
    titleEn: "Atomic Structure",
    titleAr: "البنية الذرية",
    descEn: "Protons, neutrons, electrons, electron shells, and the periodic table.",
    descAr: "البروتونات والنيوترونات والإلكترونات والأغلفة الإلكترونية والجدول الدوري.",
    difficulty: "foundation",
    topicsCount: 8,
  },
  {
    id: "bonding",
    slug: "chemical-bonding",
    icon: "🔗",
    color: "from-teal-500 to-teal-600",
    bg: "bg-teal-50",
    titleEn: "Chemical Bonding",
    titleAr: "الترابط الكيميائي",
    descEn: "Ionic, covalent, and metallic bonding with molecular structures.",
    descAr: "الترابط الأيوني والتساهمي والمعدني مع التراكيب الجزيئية.",
    difficulty: "foundation",
    topicsCount: 10,
  },
  {
    id: "stoichiometry",
    slug: "stoichiometry",
    icon: "⚖️",
    color: "from-purple-500 to-purple-600",
    bg: "bg-purple-50",
    titleEn: "Stoichiometry",
    titleAr: "القياس الكيميائي",
    descEn: "Moles, equations, calculations, and quantitative chemistry.",
    descAr: "المولات والمعادلات والحسابات والكيمياء الكمية.",
    difficulty: "intermediate",
    topicsCount: 12,
  },
  {
    id: "electrochemistry",
    slug: "electrochemistry",
    icon: "⚡",
    color: "from-yellow-500 to-orange-500",
    bg: "bg-yellow-50",
    titleEn: "Electrochemistry",
    titleAr: "الكيمياء الكهربائية",
    descEn: "Electrolysis, electrodes, half-equations, and industrial processes.",
    descAr: "التحليل الكهربائي والأقطاب ومعادلات نصف التفاعل والعمليات الصناعية.",
    difficulty: "intermediate",
    topicsCount: 9,
  },
  {
    id: "energetics",
    slug: "energetics",
    icon: "🔥",
    color: "from-red-500 to-rose-500",
    bg: "bg-red-50",
    titleEn: "Energetics",
    titleAr: "الطاقة الكيميائية",
    descEn: "Exothermic and endothermic reactions, energy profiles, and bond energies.",
    descAr: "التفاعلات الطاردة والماصة للحرارة وملفات الطاقة وطاقات الرابطة.",
    difficulty: "intermediate",
    topicsCount: 7,
  },
  {
    id: "kinetics",
    slug: "reaction-kinetics",
    icon: "⏱️",
    color: "from-indigo-500 to-indigo-600",
    bg: "bg-indigo-50",
    titleEn: "Reaction Kinetics",
    titleAr: "حركية التفاعلات",
    descEn: "Rates of reaction, catalysts, activation energy, and collision theory.",
    descAr: "معدلات التفاعل والمحفزات وطاقة التنشيط ونظرية التصادم.",
    difficulty: "advanced",
    topicsCount: 8,
  },
  {
    id: "acids-bases",
    slug: "acids-and-bases",
    icon: "🧪",
    color: "from-green-500 to-emerald-500",
    bg: "bg-green-50",
    titleEn: "Acids & Bases",
    titleAr: "الأحماض والقواعد",
    descEn: "pH scale, neutralization, salt formation, and acid properties.",
    descAr: "مقياس pH والتعادل وتكوين الأملاح وخصائص الأحماض.",
    difficulty: "foundation",
    topicsCount: 11,
  },
  {
    id: "organic-chemistry",
    slug: "organic-chemistry",
    icon: "🌿",
    color: "from-lime-500 to-green-500",
    bg: "bg-lime-50",
    titleEn: "Organic Chemistry",
    titleAr: "الكيمياء العضوية",
    descEn: "Alkanes, alkenes, alcohols, organic reactions, and polymers.",
    descAr: "الألكانات والألكينات والكحولات والتفاعلات العضوية والبوليمرات.",
    difficulty: "advanced",
    topicsCount: 15,
  },
  {
    id: "metals",
    slug: "metals",
    icon: "⚙️",
    color: "from-slate-500 to-gray-600",
    bg: "bg-slate-50",
    titleEn: "Metals & Alloys",
    titleAr: "المعادن والسبائك",
    descEn: "Metal properties, reactivity series, extraction, and corrosion.",
    descAr: "خصائص المعادن وسلسلة التفاعلية والاستخلاص والتآكل.",
    difficulty: "foundation",
    topicsCount: 9,
  },
  {
    id: "atmosphere",
    slug: "atmosphere",
    icon: "🌍",
    color: "from-sky-500 to-blue-500",
    bg: "bg-sky-50",
    titleEn: "The Atmosphere",
    titleAr: "الغلاف الجوي",
    descEn: "Air composition, pollutants, greenhouse effect, and climate chemistry.",
    descAr: "تكوين الهواء والملوثات وتأثير الاحتباس الحراري وكيمياء المناخ.",
    difficulty: "foundation",
    topicsCount: 7,
  },
];

export const blogPosts = [
  {
    id: "1",
    slug: "why-water-is-the-universal-solvent",
    titleEn: "Why Water Is Called the 'Universal Solvent'",
    titleAr: "لماذا يُسمى الماء 'المذيب العالمي'؟",
    excerptEn:
      "Water dissolves more substances than any other liquid. Here's the chemistry behind this remarkable property and why it makes life possible.",
    excerptAr:
      "يذوّب الماء مواد أكثر من أي سائل آخر. إليك الكيمياء وراء هذه الخاصية الرائعة ولماذا تجعل الحياة ممكنة.",
    category: "daily",
    date: "2024-11-15",
    readTime: 5,
    image: "/images/blog/water-solvent.jpg",
    featured: true,
    tags: ["bonding", "solutions", "daily-life"],
  },
  {
    id: "2",
    slug: "igcse-chemistry-exam-technique",
    titleEn: "Master IGCSE Chemistry: The 5 Exam Technique Mistakes to Avoid",
    titleAr: "إتقان كيمياء IGCSE: 5 أخطاء في أسلوب الامتحان يجب تجنبها",
    excerptEn:
      "Most students lose marks not because they don't know the chemistry — but because of how they answer questions. Here are the five most common mistakes.",
    excerptAr:
      "يخسر معظم الطلاب نقاطاً ليس لأنهم لا يعرفون الكيمياء — بل بسبب طريقة إجابتهم على الأسئلة. هذه الأخطاء الخمسة الأكثر شيوعاً.",
    category: "study",
    date: "2024-10-28",
    readTime: 8,
    image: "/images/blog/exam-tips.jpg",
    featured: true,
    tags: ["igcse", "exams", "study-tips"],
  },
  {
    id: "3",
    slug: "the-chemistry-of-cooking",
    titleEn: "The Chemistry Happening in Your Kitchen Right Now",
    titleAr: "الكيمياء التي تحدث في مطبخك الآن",
    excerptEn:
      "Every time you cook, you're performing chemical reactions. From Maillard browning to emulsification — cooking is applied chemistry.",
    excerptAr:
      "في كل مرة تطبخ فيها، تُجري تفاعلات كيميائية. من تحمير مايار إلى الاستحلاب — الطبخ هو كيمياء تطبيقية.",
    category: "daily",
    date: "2024-10-10",
    readTime: 6,
    image: "/images/blog/cooking-chemistry.jpg",
    featured: false,
    tags: ["reactions", "organic", "daily-life"],
  },
  {
    id: "4",
    slug: "understanding-moles",
    titleEn: "Demystifying Moles: The Concept That Unlocks Stoichiometry",
    titleAr: "كشف أسرار الموْل: المفهوم الذي يفتح أبواب القياس الكيميائي",
    excerptEn:
      "The mole is the most important concept in chemistry — and the most misunderstood. Here's a clear, intuitive explanation.",
    excerptAr:
      "الموْل هو أهم مفهوم في الكيمياء — والأكثر سوء فهم. إليك شرح واضح وبديهي.",
    category: "concepts",
    date: "2024-09-22",
    readTime: 7,
    image: "/images/blog/moles.jpg",
    featured: false,
    tags: ["stoichiometry", "moles", "calculations"],
  },
  {
    id: "5",
    slug: "study-plan-igcse-chemistry",
    titleEn: "The 12-Week IGCSE Chemistry Study Plan That Actually Works",
    titleAr: "خطة دراسة كيمياء IGCSE لـ 12 أسبوعاً تنجح فعلاً",
    excerptEn:
      "A structured, week-by-week study schedule designed to take you from confused to confident in every IGCSE Chemistry topic.",
    excerptAr:
      "جدول دراسي منظم أسبوعاً بأسبوع مصمم لنقلك من الارتباك إلى الثقة في كل موضوع من مواضيع كيمياء IGCSE.",
    category: "study",
    date: "2024-09-05",
    readTime: 10,
    image: "/images/blog/study-plan.jpg",
    featured: false,
    tags: ["igcse", "study-plan", "revision"],
  },
  {
    id: "6",
    slug: "acids-in-everyday-life",
    titleEn: "Acids and Bases Are Everywhere — And Here's the Proof",
    titleAr: "الأحماض والقواعد في كل مكان — وهذا هو الدليل",
    excerptEn:
      "From lemon juice (pH 2) to baking soda (pH 9), acids and bases shape the food we eat, the products we use, and even our own blood.",
    excerptAr:
      "من عصير الليمون (pH 2) إلى صودا الخبز (pH 9)، تُشكّل الأحماض والقواعد الطعام الذي نأكله والمنتجات التي نستخدمها وحتى دمنا.",
    category: "daily",
    date: "2024-08-18",
    readTime: 5,
    image: "/images/blog/acids.jpg",
    featured: false,
    tags: ["acids-bases", "daily-life", "ph"],
  },
];

export const resources = [
  {
    id: "1",
    titleEn: "Complete IGCSE Chemistry Revision Notes",
    titleAr: "ملاحظات مراجعة كيمياء IGCSE الكاملة",
    descEn: "Comprehensive, exam-focused notes covering all IGCSE Chemistry topics with diagrams and key points.",
    descAr: "ملاحظات شاملة مركزة على الامتحانات تغطي جميع مواضيع كيمياء IGCSE مع الرسوم البيانية والنقاط الرئيسية.",
    type: "notes",
    topic: "all",
    difficulty: "all",
    pages: 85,
    format: "PDF",
    premium: false,
    downloads: 1247,
    rating: 4.9,
    icon: "📚",
  },
  {
    id: "2",
    titleEn: "Atomic Structure Deep Dive Worksheet",
    titleAr: "ورقة عمل تعمق البنية الذرية",
    descEn: "50 exam-style questions on atomic structure, isotopes, and electronic configuration.",
    descAr: "50 سؤالاً بأسلوب الامتحان حول البنية الذرية والنظائر والتكوين الإلكتروني.",
    type: "worksheets",
    topic: "atomic-structure",
    difficulty: "foundation",
    pages: 12,
    format: "PDF",
    premium: false,
    downloads: 892,
    rating: 4.8,
    icon: "📝",
  },
  {
    id: "3",
    titleEn: "Organic Chemistry Complete Pack",
    titleAr: "حزمة الكيمياء العضوية الكاملة",
    descEn: "Full set of notes, worksheets, and past paper questions for organic chemistry. Covers all reaction mechanisms.",
    descAr: "مجموعة كاملة من الملاحظات وأوراق العمل وأسئلة الأوراق السابقة للكيمياء العضوية. تغطي جميع آليات التفاعل.",
    type: "revision",
    topic: "organic-chemistry",
    difficulty: "advanced",
    pages: 40,
    format: "PDF",
    premium: true,
    downloads: 0,
    rating: 5.0,
    icon: "🌿",
  },
  {
    id: "4",
    titleEn: "Stoichiometry Calculation Workbook",
    titleAr: "كتاب حسابات القياس الكيميائي",
    descEn: "Step-by-step calculation examples and practice questions for moles, equations, and yield calculations.",
    descAr: "أمثلة حسابية خطوة بخطوة وأسئلة تدريبية لحسابات المولات والمعادلات والإنتاج.",
    type: "worksheets",
    topic: "stoichiometry",
    difficulty: "intermediate",
    pages: 24,
    format: "PDF",
    premium: false,
    downloads: 634,
    rating: 4.7,
    icon: "⚖️",
  },
  {
    id: "5",
    titleEn: "IGCSE Past Paper Question Bank — Acids & Bases",
    titleAr: "بنك أسئلة أوراق IGCSE السابقة — الأحماض والقواعد",
    descEn: "Curated past paper questions from 2015–2023 on acids, bases, and salts, with full mark schemes.",
    descAr: "أسئلة منتقاة من الأوراق السابقة من 2015-2023 حول الأحماض والقواعد والأملاح مع مخططات علامات كاملة.",
    type: "practice",
    topic: "acids-bases",
    difficulty: "intermediate",
    pages: 35,
    format: "PDF",
    premium: true,
    downloads: 0,
    rating: 4.9,
    icon: "🧪",
  },
  {
    id: "6",
    titleEn: "Energetics & Kinetics Summary Sheets",
    titleAr: "ملخصات الطاقة والحركية الكيميائية",
    descEn: "Concise one-page summaries of energetics and kinetics key concepts, ideal for last-minute revision.",
    descAr: "ملخصات موجزة لصفحة واحدة للمفاهيم الرئيسية في الطاقة والحركية، مثالية للمراجعة في اللحظة الأخيرة.",
    type: "notes",
    topic: "energetics",
    difficulty: "intermediate",
    pages: 4,
    format: "PDF",
    premium: false,
    downloads: 1089,
    rating: 4.8,
    icon: "🔥",
  },
];

export const shopProducts = [
  {
    id: "1",
    titleEn: "Ultimate IGCSE Chemistry Revision Pack",
    titleAr: "حزمة مراجعة كيمياء IGCSE الشاملة",
    descEn: "The complete revision toolkit: notes, worksheets, flashcards, and exam technique guide for all topics.",
    descAr: "مجموعة المراجعة الكاملة: ملاحظات وأوراق عمل وبطاقات تعليمية ودليل أسلوب الامتحان لجميع المواضيع.",
    price: 24.99,
    originalPrice: 39.99,
    category: "revision",
    badge: "bestseller",
    icon: "📦",
    comingSoon: false,
    rating: 4.9,
    reviews: 47,
  },
  {
    id: "2",
    titleEn: "Organic Chemistry Mastery Notes",
    titleAr: "ملاحظات إتقان الكيمياء العضوية",
    descEn: "Detailed, visual notes on all organic chemistry topics with reaction maps and memory frameworks.",
    descAr: "ملاحظات مفصلة وبصرية لجميع مواضيع الكيمياء العضوية مع خرائط التفاعل وأطر الذاكرة.",
    price: 12.99,
    originalPrice: null,
    category: "notes",
    badge: "new",
    icon: "🌿",
    comingSoon: false,
    rating: 4.8,
    reviews: 23,
  },
  {
    id: "3",
    titleEn: "1000 IGCSE Chemistry Practice Questions",
    titleAr: "1000 سؤال تدريبي لكيمياء IGCSE",
    descEn: "A comprehensive question bank organized by topic and difficulty, with full worked solutions.",
    descAr: "بنك أسئلة شامل منظم حسب الموضوع والصعوبة مع حلول كاملة.",
    price: 19.99,
    originalPrice: 29.99,
    category: "worksheets",
    badge: "popular",
    icon: "📝",
    comingSoon: false,
    rating: 4.7,
    reviews: 31,
  },
  {
    id: "4",
    titleEn: "Chemistry for Beginners: E-Book",
    titleAr: "الكيمياء للمبتدئين: كتاب إلكتروني",
    descEn: "A beginner-friendly guide that makes foundational chemistry concepts crystal clear with illustrations.",
    descAr: "دليل مناسب للمبتدئين يجعل مفاهيم الكيمياء الأساسية واضحة تماماً مع الرسوم التوضيحية.",
    price: 9.99,
    originalPrice: null,
    category: "books",
    badge: null,
    icon: "📖",
    comingSoon: false,
    rating: 4.6,
    reviews: 18,
  },
  {
    id: "5",
    titleEn: "Advanced Calculations Workbook",
    titleAr: "كتاب الحسابات المتقدمة",
    descEn: "Step-by-step guidance for the hardest calculation questions in IGCSE Chemistry with 200 worked examples.",
    descAr: "إرشادات خطوة بخطوة لأصعب أسئلة الحسابات في كيمياء IGCSE مع 200 مثال محلول.",
    price: 14.99,
    originalPrice: null,
    category: "worksheets",
    badge: null,
    icon: "🔢",
    comingSoon: true,
    rating: 0,
    reviews: 0,
  },
  {
    id: "6",
    titleEn: "Stoichiometry Flashcard Set",
    titleAr: "مجموعة بطاقات القياس الكيميائي التعليمية",
    descEn: "150 printable flashcards covering all stoichiometry formulas, methods, and key terms.",
    descAr: "150 بطاقة تعليمية قابلة للطباعة تغطي جميع صيغ القياس الكيميائي والطرق والمصطلحات الرئيسية.",
    price: 7.99,
    originalPrice: null,
    category: "revision",
    badge: null,
    icon: "🗂️",
    comingSoon: true,
    rating: 0,
    reviews: 0,
  },
];

export const testimonials = [
  {
    id: "1",
    nameEn: "Ahmed K.",
    nameAr: "أحمد ك.",
    roleEn: "IGCSE Student, A* Grade",
    roleAr: "طالب IGCSE، درجة A*",
    textEn:
      "Sara's teaching transformed my understanding of chemistry. I went from a C to an A* in four months. Her explanations are so clear and her exam technique tips are invaluable.",
    textAr:
      "غيّر تدريس سارة فهمي للكيمياء. انتقلت من C إلى A* في أربعة أشهر. شروحاتها واضحة جداً ونصائح أسلوب الامتحان لا تقدر بثمن.",
    rating: 5,
    country: "Egypt",
  },
  {
    id: "2",
    nameEn: "Sarah M.",
    nameAr: "سارة م.",
    roleEn: "Parent of IGCSE Student",
    roleAr: "والدة طالب IGCSE",
    textEn:
      "My daughter struggled with chemistry for years. After just 2 months with Sara, her confidence and grades improved dramatically. Highly recommend!",
    textAr:
      "عانت ابنتي مع الكيمياء لسنوات. بعد شهرين فقط مع سارة، تحسنت ثقتها ودرجاتها بشكل ملحوظ. أوصي بشدة!",
    rating: 5,
    country: "UAE",
  },
  {
    id: "3",
    nameEn: "James T.",
    nameAr: "جيمس ت.",
    roleEn: "International Student",
    roleAr: "طالب دولي",
    textEn:
      "The resources Sara creates are genuinely outstanding. Her revision notes are the best I've seen — clear, comprehensive, and beautifully organized.",
    textAr:
      "الموارد التي تنشئها سارة رائعة حقاً. ملاحظات مراجعتها هي الأفضل التي رأيتها — واضحة وشاملة ومنظمة بشكل جميل.",
    rating: 5,
    country: "UK",
  },
  {
    id: "4",
    nameEn: "Fatima R.",
    nameAr: "فاطمة ر.",
    roleEn: "Self-Study Learner",
    roleAr: "متعلمة بالتعليم الذاتي",
    textEn:
      "I used Sara's notes to study for my IGCSE without a tutor. I passed with an A, largely thanks to how well-structured her materials are.",
    textAr:
      "استخدمت ملاحظات سارة للدراسة لـ IGCSE بدون معلم خصوصي. نجحت بدرجة A، ويعود الفضل إلى حد بعيد لمدى تنظيم موادها.",
    rating: 5,
    country: "Saudi Arabia",
  },
];

export const kidsActivities = [
  {
    id: "1",
    icon: "🌋",
    titleEn: "Baking Soda Volcano",
    titleAr: "بركان صودا الخبز",
    descEn: "The classic acid-base reaction made spectacular with red food coloring.",
    descAr: "تفاعل حمض-قاعدة الكلاسيكي مع لون احمر مبهر.",
    ageRange: "5-10",
    difficulty: "easy",
    category: "experiments",
  },
  {
    id: "2",
    icon: "🌈",
    titleEn: "Rainbow in a Glass",
    titleAr: "قوس قزح في كأس",
    descEn: "Explore density by layering liquids of different densities to create a rainbow.",
    descAr: "استكشف الكثافة من خلال تطبيق سوائل ذات كثافات مختلفة لإنشاء قوس قزح.",
    ageRange: "6-12",
    difficulty: "easy",
    category: "experiments",
  },
  {
    id: "3",
    icon: "🔮",
    titleEn: "Invisible Ink Messages",
    titleAr: "رسائل الحبر الخفي",
    descEn: "Use lemon juice to write secret messages revealed by heat — chemistry magic!",
    descAr: "استخدم عصير الليمون للكتابة برسائل سرية تُكشف بالحرارة — سحر كيميائي!",
    ageRange: "7-14",
    difficulty: "easy",
    category: "experiments",
  },
  {
    id: "4",
    icon: "🎨",
    titleEn: "Chromatography Art",
    titleAr: "فن الكروماتوغرافيا",
    descEn: "Separate ink colors using water and coffee filters to reveal hidden hues.",
    descAr: "افصل ألوان الحبر باستخدام الماء وفلاتر القهوة لكشف الألوان المخفية.",
    ageRange: "8-14",
    difficulty: "medium",
    category: "experiments",
  },
];

export const services = [
  {
    id: "tutoring",
    icon: "🎓",
    priceFrom: 30,
    durationMinutes: 60,
    available: true,
  },
  {
    id: "igcse",
    icon: "📋",
    priceFrom: 25,
    durationMinutes: 90,
    available: true,
  },
  {
    id: "studyPlan",
    icon: "📅",
    priceFrom: 49,
    durationMinutes: null,
    available: true,
  },
  {
    id: "content",
    icon: "✍️",
    priceFrom: null,
    durationMinutes: null,
    available: true,
  },
  {
    id: "worksheets",
    icon: "📄",
    priceFrom: null,
    durationMinutes: null,
    available: true,
  },
  {
    id: "group",
    icon: "👥",
    priceFrom: 15,
    durationMinutes: 90,
    available: true,
  },
];
